### ISSUE TITLE
Fails with "ValueError: Missing some input keys: {'unit_tests', 'pre_commit_hooks', 'github_actions', 'dockerization'}"

### ISSUE THREAD

**Issue by xpluscal** [ajndkr/boilerplate-x#3]

**Comment by ajndkr** [comment]
Hi! thanks for trying out boilerplate-x!

Can you please share the command or steps you followed which threw this error?

**Comment by ajndkr** [comment]
@xpluscal I've identified the bug and pushed a fix with #4. Can you please pull the latest changes from the `main` branch and try again? thanks!
